### ISSUE TITLE
Media Keys Will Not Bind in KDE (even with Keybinder)

### ISSUE THREAD

**Issue by trey-jones** [pithos/pithos#595]
What baffles me is that Play/Pause/Skip worked fine on a clean install of Manjaro KDE, even without Keybinder.  At some point either through an update or installing some other software, possibly enabling MPRIS/KDEConnect (which works fine) it stopped working.  Here are the relevant logs:

```INFO - plugin:enable:53 - Preparing module mediakeys
DEBUG - mediakeys:on_new_finish:112 - DBus binding failed
INFO - plugin:_enable:59 - Enabling module mediakeys

** (pithos:518): WARNING **: 08:53:34.056: Binding 'XF86AudioPlay' failed!
ERROR - mediakeys:on_enable:149 - Failed to bind media keys with Keybinder
```

Pacman info (from AUR):

```Name            : pithos
Version         : 1.5.0-1
Description     : Native Pandora Radio client
Architecture    : any
URL             : https://pithos.github.io/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : gtk3  python-gobject  libsecret  python-cairo  gst-plugins-good  gst-libav  gst-plugins-base
Optional Deps   : libkeybinder3: for media keys plugin [installed]
                  libappindicator-gtk3: Unity indicator applet support [installed]
                  python-pacparser: PAC proxy support
                  python-pylast: Last.fm scrobbling support
                  python-systemd: Logging to the system journal
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 780.00 KiB
Packager        : Unknown Packager
Build Date      : Mon 14 Oct 2019 05:59:10 PM EDT
Install Date    : Mon 14 Oct 2019 05:59:12 PM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```
Same happens on master - I've done some light debugging, and I might have time to make a PR if someone shoves me in the right direction.  I'm fairly new to KDE and I'm not sure if it's as simple as adding something to `de_busnames` or whether it's more of a KDE problem than a Pithos problem.

**Comment by JasonLG1979** [comment]
X or Wayland? Because I'm not sure that Keybinder works with Wayland? Otherwise we don't do anything to bind the mediaKeys in KDE. I'm not even sure they have a DBus interface specifically for binding mediaKeys. Last I looked they used MPRIS for mediaKey binding.

**Comment by TingPing** [comment]
Keybinder is X specific but Pithos won't even attempt to use it on Wayland.

**Comment by trey-jones** [comment]
I am on X.  As I said, the baffling part is that it worked, even without Keybinder on a fresh install.

**Comment by JasonLG1979** [comment]
@TingPing We might want to check to see if [```Keybinder.supported()```](https://lazka.github.io/pgi-docs/#Keybinder-3.0/functions.html#Keybinder.supported) is of any use at all?

**Comment by JasonLG1979** [comment]
@trey-jones other then that Keybinder is an external project and pretty much a BlackBox in that it really doesn't expose much of anything to the outside world. The entire interface consists of 6 functions and 1 callback. Basically from what we can see it either works or it doesn't with not much explanation either way.

**Comment by JasonLG1979** [comment]
@TingPing it looks like basically ```Keybinder.supported()``` is basically just checking to make sure keybinder is running in X. (Which we already do). And is checked in the bind function under the hood.

Looking at the source code,
```Keybinder.supported()```
Just returns:
```GDK_IS_X11_DISPLAY(gdk_display_get_default());```

I'm wonder if that's not the right way to check for X? You would know more than me...

**Comment by TingPing** [comment]
> I am on X. As I said, the baffling part is that it worked, even without Keybinder on a fresh install.

In that case Pithos wasn't doing the binding and it was some automatic MPRIS support in KDE so that is probably where to look. We did change our MPRIS name this last release but that shouldn't be relevant.

**Comment by ForLoveOfCats** [comment]
A recent KDE Plasma 5 update seems to have broken it's MPRIS support. Under Plasma 5.16.5 MPRIS works with neither Pithos nor VLC whereas they both work under 5.16.4.

**Comment by trey-jones** [comment]
Probably related, but I don't know enough about the parts to say:
I can use KDE connect on my phone to control Pithos.  I was given to understand that MPRIS was the mechanism behind this.  It also occurred to me that there could be some conflict between KDE Connect and the media keys plugin.

**Comment by ForLoveOfCats** [comment]
After noticing that VLC once again works with Plasma 5's MPRIS implementation while a freshly built copy of Pithos from master still does not I decided to do some Googling. It seems that around the versions I specified the KDE devs made their MPRIS more strict in what it accepts. https://www.reddit.com/r/kde/comments/czmyq8/last_plasma_update_broke_media_controller/

And here is another project facing the same issue https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3618

So this means that either Pithos is incorrectly interfacing with MPRIS or Plasma 5 is being *to* strict. It is probably the former as VLC now works again after a few months of system updates (I'm assuming that VLC fixed it on their end) and the cause of Audacious' not working was identified as its own incorrect usage of MPRIS.

**Comment by JasonLG1979** [comment]
> So this means that either Pithos is incorrectly interfacing with MPRIS or Plasma 5 is being _to_ strict.

There is absolutely no chance that Pithos' MPRIS implementation is borked in any way. To my knowledge our implementation is the most complete and by the book implementation of any player you will find.

The KDE contributor mentions the ```SupportedUriScheme``` and ```SupportedMimeTypes``` properties specifically, Those properties are indeed required and are of type ```as``` (array of strings) they ofc course would indicate the uri scheme and file types that your player could open/play via the ```OpenUri``` method. Since Pithos can not open external (as in not from Pandora) media files both properties return ```['',]```, that is an array containing a single empty string. Those are perfectly valid values for those properties to indicate that Pithos does not support any uri schemes or mimetypes, again indicating that we can not open media files.

If this is the case I would file a bug report with Plasma.

**Comment by TingPing** [comment]
Should it not just be an empty list, not an empty string?

**Comment by JasonLG1979** [comment]
> Should it not just be an empty list, not an empty string?

I would not think it would matter. I think it's a case of someone getting to strict. When dealing with something like MPRIS you should deal with absent or empty values better. In this particular case an empty array, an array with just an empty string and the total absents of the property should be interpenetrated the same way.

**Comment by JasonLG1979** [comment]
If they choke completely on something that trivial I'm not putting much stock in their implementation. They should be more granular in their approach as far as how properties correspond to exposed functionality. Especially when it comes to MPRIS. I'd bet that A LOT of players don't work.

**Comment by JasonLG1979** [comment]
@TingPing it appears as though they are specifically looking at ```SupportedUriScheme``` and ```SupportedMimeTypes```. I have no idea what ```isValid()``` actually checks for but I'd guess that an empty value doesn't pass.

https://github.com/KDE/plasma-workspace/blob/fbdb18bfd17027c340cbfc15294916d6ae93bee9/dataengines/mpris2/mpris2engine.cpp#L133-L134

This is clearly a bug on their part as it is very possible for a player to not support opening anything.

I'm not in favor of lying about what we support.

@ForLoveOfCats I would file a bug with KDE and link to this. This is not our bug.

**Comment by ForLoveOfCats** [comment]
Neither changing `SupportedUriScheme` and `SupportedMimeTypes` to empty lists nor to lists with a single non-empty string affected the issue in the slightest. Also I cannot find any MPRIS errors being reported over dbus nor is plasmashell reporting any errors.

**Comment by TingPing** [comment]
@JasonLG1979 I agree it shouldn't really matter nor is relevant to this issue but I think it is more correct.

**Comment by JasonLG1979** [comment]
> I agree it shouldn't really matter but I think it is more correct.

I'm fine with an empty array.

**Comment by JasonLG1979** [comment]
> Neither changing `SupportedUriScheme` and `SupportedMimeTypes` to empty lists nor to lists with a single non-empty string affected the issue in the slightest. Also I cannot find any MPRIS errors being reported over dbus nor is plasmashell reporting any errors.

They're more than likely looking for an actual value like ```https``` and ```audio/mpeg``` as in the Google Play Music™ Desktop Player [commit](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/a1d6d348b8fa6a0f5db3b473aa60384581e77d6d) that depending on who you ask fixed the issue for them.

My concern is that they actually use the ```OpenUri``` [method](https://github.com/KDE/plasma-workspace/search?l=C%2B%2B&q=OpenUri). So filling in `SupportedUriScheme` and `SupportedMimeTypes` would basically be advertising a feature we do not support. ```OpenUri``` [exists in our implementation](https://github.com/pithos/pithos/blob/master/pithos/plugins/mpris.py#L697-L700) but it doesn't actually do anything. Because ofc Pithos doesn't support opening external media files. So the result would be that a user might have the option to open media with Pithos but it wouldn't actually do anything. That's just broken by design.

IMHO they should be treating the absence of values for those properties to simply mean don't use the OpenUri method but instead they throw the baby out with the bathwater.

**Comment by JasonLG1979** [comment]
@ForLoveOfCats [Here](https://phabricator.kde.org/D22596) is the commit that breaks MPRIS. I searched for plasma-workspace in the KDE bug tracker to file a bug but couldn't come up with anything.

@TingPing IMHO this should be closed as not our bug.

As a work around we could probably put gibberish as a return value for those properties and hope a client would check for matches before they tried to use the OpenUri method (which it should never since our values would be gibberish) and log when the method is used to indicate that it's not supported.

**Comment by JasonLG1979** [comment]
We could use ```example``` for the ```SupportedUriScheme``` which is valid according to this [list](https://en.wikipedia.org/wiki/List_of_URI_schemes) but basically meaningless. And ```application/octet-stream``` for the ```SupportedMimeTypes```? No actual media file should match those.

**Comment by TingPing** [comment]
@JasonLG1979 I agree its not our bug and I don't think we should return nonsense to workaround it.

I would like somebody to report this upstream. Until then this can stay around (its labeled `upstream` (aka not our bug) already).

**Comment by JasonLG1979** [comment]
> I would like somebody to report this upstream. Until then this can stay around (its labeled `upstream` already).

Done.

https://bugs.kde.org/show_bug.cgi?id=416102

**Comment by TingPing** [comment]
@JasonLG1979 I love you man but you suck at titling bugs, stop being insulting and calling everything broken, be technically precise, etc.

**Comment by ForLoveOfCats** [comment]
This commit https://github.com/pithos/pithos/commit/ff4c5b983e4fb1f53e9b309d1b90ac2a1aea0e5e does not fix the issue, nor does any other potential fix that has been discussed here. I've been testing each idea as they've been suggested

**Comment by JasonLG1979** [comment]
> This commit [ff4c5b9](https://github.com/pithos/pithos/commit/ff4c5b983e4fb1f53e9b309d1b90ac2a1aea0e5e) does not fix the issue (though if it is more "correct" then of course that is worth making that change), nor does any other potential fix that has been discussed here. I've been testing each idea as they've been suggested

I don't know what it could be then. Our MPRIS implementation hasn't changed with the exception of that last commit in 3 years?

**Comment by dbfin** [comment]
So, do you know which version of Pithos should include the fix?

**Comment by retrodaredevil** [comment]
I have this same problem. I recently switched my desktop to KDE Plasma from Gnome 3 and am getting this problem. What's weird is that when I use KDE Connect I am able to pause and play the music from my phone, but I cannot do that from the media player.

**Comment by JasonLG1979** [comment]
@TingPing do you want to do a bugfix/maintenance release? And push it to flathub?

**Comment by retrodaredevil** [comment]
So after running `flatpak update io.github.Pithos`, it's working now. I forgot that flatpak doesn't automatically update with apt updates. So I guess this was fixed somewhere between the version I was running and 1.5.0.

**Comment by dbfin** [comment]
@retrodaredevil We all run 1.5.0 including the OP. Mine is version 1.5.0-1 in Arch Linux's AUR. Not sure how exactly these versions correspond to each other in different OS. It would be nice if say the updated and fixed version would be called 1.5.1, not something like 1.5.0-2 or anything like that, as, for example, flatpak does not even show this fourth number in the Pithos's version. Neither does Pithos itself.

**Comment by dbfin** [comment]
@TingPing BTW, I just checked, and it seems like you are actually the maintainer of the AUR package, so I guess you would be first to know when that AUR package is going to be updated with the fix. Thanks!

**Comment by dbfin** [comment]
@TingPing Upon further checking, I figured that while you are indeed listed as the maintainer of the `pithos` package in the AUR, the actual maintainer (also listed in PKGBUILD) is someone else, so I should probably contact them as well. 

Regardless, could you guys bump these recent changes to v1.5.1, so it would be (almost) automatically updated in the AUR? Without the official change in the version, the AUR package can only refer to the latest official version, which is v1.5.0. Then I will mark the AUR package as out-of-date.

**Comment by dbfin** [comment]
So, would anyone respond please?

**Comment by TingPing** [comment]
I would like to make a release but my schedule is a bit busy.

**Comment by dbfin** [comment]
Well, it is a public open source project, so someone else then should maintain it as well. It seems a few years ago when I contributed a bit to this project, both you and Jason were mostly active working on Pithos; it seems Jason is still very responsive -- maybe @JasonLG1979 you can do it yourself?

**Comment by dbfin** [comment]
@TingPing Just don't take my words personally. :) I am not questioning your credibility as the maintainer of this project or anything. In fact, this year is weird, so maybe you currently have some personal reasons for delays, and if so, I apologize. I just assumed that since you are now not responding for weeks, and since this issue was actually resolved more than half a year ago, but the fix is still not released, you might be simply busy with some other projects or work, and might want to look into someone else you know to help maintaining this one, for example, by issuing bugfix releases etc.

**Comment by JasonLG1979** [comment]
@dbfin I'm not the maintainer @TingPing is. I don't have access to the AUR system. You could use the flatpak? The flatpak has the  [fix](https://github.com/pithos/pithos/pull/608). Pithos is pretty much in maintenance mode AFAIC. It's pretty much feature complete barring a redesign.

**Comment by JasonLG1979** [comment]
As far as packaging is concerned flatpak is the official package. I have no interest in packaging Pithos (or anything else really,lol) I'm thinking @TingPing probably fell about, if not exactly, the same way. Flatpak is the way to the future. Package once and done.

**Comment by JasonLG1979** [comment]
There's nothing stopping you from creating your own PKGBUILD.

**Comment by dbfin** [comment]
@JasonLG1979 

> I have no interest in packaging Pithos...

I mentioned you only because you are the only one from people I know in this project still responding in a timely manner -- other than that I don't care.

> As far as packaging is concerned flatpak is the official package... Flatpak is the way to the future. Package once and done.

There are other alternatives for the future, and some are even much bigger, better funded and supported. But all these systems have their downsides. And regardless, usual package systems will still exists -- it is not that everyone wants every piece of software in its own sandbox. I, for example, don't want to install and use flatpak as yet another package manager just to run Pithos.

The main point is that, regardless of the future, as long as there are still standard ways to distribute packages, it is important to support them. And these systems depend on the versions of software. Version 1.5.0 was introduced 1 year ago in October 2019. Since then you had a few changes and improvements, and more importantly bug fixes. But without you marking those changes at least as v1.5.1, no package maintainer in any OS can do anything about it. They simply have no new Pithos version to package against.

> There's nothing stopping you from creating your own PKGBUILD.

This is not true. First, I did not say that I have time to maintain a Pithos package in AUR. Second, there is no point to create a parallel package in AUR that would do the same as the official one. Third, what would I do in this new PKGBUILD? Refer to `/pithos/pithos/archive/master.tar.gz` instead of `/pithos/pithos/releases/download/${pkgver}/pithos-${pkgver}.tar.xz` to download the `master` branch that would include new bug fixes? But then I would get at least two problems: first, not every commit to the `master` branch is self-contained, and official versions exist exactly to mark those points in time where it makes sense to stop and publish; second, every commit to the `master` branch would cause a change in at least `sha256sums`, so I would have to update PKGBUILD literally after every single commit to your repository.

> I'm thinking @TingPing probably fells about, if not exactly, the same way.

I am not sure as @TingPing actually said: "I would like to make a release but my schedule is a bit busy."

---

I am not even sure what the problem is. It is so simple, because, this is Python, you distribute it as it is, in the source. So, bumping a version should take like no more than 15 minutes.

On the other hand, this would benefit hundres if not thousands of people across distributions.

**Comment by JasonLG1979** [comment]
@dbfin well it's open source so you are pretty much free to do with Pithos as you see fit (within the licence ofc) as are we. We have no more of an obligation to package Pithos then you do. 15 min or 15 hours, it doesn't matter. @TingPing's time is his own to do with what he pleases and see fit. You're beating a dead horse. Just stop. @TingPing will update Pithos when and if he chooses. no sooner or later if at all. If you do not like that then fork and package Pithos yourself.

**Comment by dbfin** [comment]
Stop getting all that emotional. You turn this into obvious and irrelevant.

BTW, this is the second time in a row you speak on behalf of @TingPing. Appeal to authority. I just mentioned you because you were responsive. But please speak for yourself: "Thanks for mentioning me, but I, Jason, have no interest in maintaining Pithos versions besides flatpak, which I think is the only future." Concise and clear to everyone, and we all then just wait for TingPing's input on this. I think it makes sense if @TingPing would speak on his own behalf from now on.

All I heard is @TingPing said 

> I would like to make a release but my schedule is a bit busy.

**Comment by JasonLG1979** [comment]
I'm not getting emotional. You just keep beating a dead horse. @TingPing has already given his answer. Accept it and wait or don't and do what you will with the Pithos source. Either way you keep going on and on and on here certainly isn't going to make anything happen any faster if anything it going to make @TingPing and I just unsubscribe from this issue and you can complain in a vacuum.

**Comment by dbfin** [comment]
@JasonLG1979 I am not even sure why you do this all first of all. I addressed @TingPing, and was waiting for his response, when you appeared with lecturing me and the community on your no-obligation morale. So, please, go ahead, and unsubscribe.

**Comment by JasonLG1979** [comment]
#608 fixes and closes this issue.

**Comment by TingPing** [comment]
https://github.com/pithos/pithos/releases/tag/1.5.1

**Comment by dbfin** [comment]
@TingPing Thank you! Glad to see you keep things up. Very much appreciated.
