### ISSUE TITLE
pithos stops playing randomly

### ISSUE THREAD

**Issue by gregsheremeta** [pithos/pithos#94]
Pithos stops playing randomly while moving to the next song after a song finishes.

The next song gets highlighted, but it never starts. Also, the current time on that next song isn't 0:00 -- it's usually 3:xx or 4:xx -- I suspect this invalid start time is actually the end time of the previous song. Perhaps we're missing clearing out a variable somewhere.

This appears to be completely random.

Duplicated using 1.0.0 on Fedora 20 and Ubuntu 14.04.

**Comment by JasonLG1979** [comment]
@gregsheremeta 

It's been a while but I believe I've come up with a pretty good workaround for this bug. Still testing it but basically it amounts to keeping track of last time of the previous song(if there was a previous song) and if the current song's start time is more than the previous song's last time do a flushing seek to the beginning of the song instead of reloading the url. It seems to work pretty well. Last night I let Pithos run for 10 hours while I was at work and it played right through 29 instances of the bug(I put a counter in the checking function)

**Comment by gregsheremeta** [comment]
I think Glenn may have fixed the actual bug in https://github.com/pithos/pithos/pull/155

There is still a gstreamer deadlock potential, but I'm not hitting it in this version.

Can you pull his copy down and give it a try for a week?

**Comment by JasonLG1979** [comment]
I added his PPA in ubuntu 14.10 and I haven't got a single deadlock in a couple days, where as before I was getting a deadlock every few songs. But I was still running into the random stops. I'll test his fork for a week.

**Comment by JasonLG1979** [comment]
One of these days I'll put in a pull request for a couple little minor bugs like the whole UI loop thing and screwed up notifications when there are "&'s" in the song titles.

**Comment by JasonLG1979** [comment]
Nope doesn't fix it. Just had a random stop.

**Comment by JasonLG1979** [comment]
I don't think it's anything Pithos is doing wrong. The fact that a flushing seek back to 0 works to clear the bug leads me to think that for some reason or another Gstreamer every now and then just isn't clearing the position info in between songs.

**Comment by JasonLG1979** [comment]
I've updated my fork with my most latest work around.

**Comment by ShapeShifter499** [comment]
I'm sorry got lost in all this, I was busy.  Ok so did you revert to useing Gstreamer with a patch to try to fix the lockup?

**Comment by gregsheremeta** [comment]
> Nope doesn't fix it. Just had a random stop.

Yeah, I had two yesterday. Damn.

**Comment by JasonLG1979** [comment]
I've been playing with the async_done message. From what I understand that message is emitted when the pipeline successfully goes from ready to paused.(in my case anyway?) and it seems promising. In my fork the pipeline goes to ready, the new source is added then the pipeline is set to paused and waits for buffer messages to go to play and in the buffer function I have a catch that doesn't allow a state change to play unless the async_done message is received. What I'm trying to test is if trying to set the pipeline to play before the state change from ready to paused is complete is causing the lockup.

**Comment by JasonLG1979** [comment]
@gregsheremeta 
I think that the async_done message is the key. Basically I've been playing around with not messing with the pipeline at all until after that message, not so much as even position or duration queries. I ran Pithos for 24 hours straight yesterday with not a single problem.

**Comment by JasonLG1979** [comment]
The whole waiting for the async message before messing with seems to also work in gstreamer 1.2(the version that doesn't download buffer mp3's) I'm going to do some more testing and then I'll have some code for you guys to review in a few days. Combined with the gstreamer patch that that stops the random deadlocks it should provide hassle free listening for the 1st time in about a year.

**Comment by JasonLG1979** [comment]
Thinking about ditching play in and building a custom pipeline.

**Comment by JasonLG1979** [comment]
*playbin

**Comment by MarkLodato** [comment]
Any updates?  I've had to stop using Pithos and switch to the web client due to this bug. :(

**Comment by JasonLG1979** [comment]
I'm working on it. Along the way I've changed a lot of Pithos's internals. You can see if my fork works for you.
https://github.com/JasonLG1979/pithos/tree/JasonLG1979-Possible-fix-to-the-lockup-bug

**Comment by gregsheremeta** [comment]
@JasonLG1979 didn't you nail it down in the other thread that disabling download buffering fixes all? I haven't had a single hang in two weeks with that tweak.

So, I think we should release a point release with just that tweak -- you know, so the project is *usable* again :-/

**Comment by JasonLG1979** [comment]
> @JasonLG1979 didn't you nail it down in the other thread that disabling download buffering fixes all? I haven't had a single hang in two weeks with that tweak.

Yep, that seems to do it. I haven't had any problems since either.

> So, I think we should release a point release with just that tweak -- you know, so the project is usable again :-/

I think that's a good idea. No download buffering isn't a huge loss. It was just there because years ago Pithos didn't have proper handling of buffering.

Like I said. I've changed A LOT of the guts(for the better IMHO) along the way I also enabled the display of track time in mpris(for widgets that actually show it like the GNOME sound menu extension) and fixed "now playing" in last.fm. I'm working on showing the tracklist in mpris and syncing last.fm ratings with Pandora ratings. My idea is basically in the last.fm plugin I'd like to have an option that allows you to automatically love a song in Pithos if it's loved on last.fm.

**Comment by TingPing** [comment]
@JasonLG1979 That is great and all that you are re-writing the program but it would be nice to focus on something to get it merged.

**Comment by gregsheremeta** [comment]
lol.

In other words, one PR with just the download buffering fix, please :)

**Comment by JasonLG1979** [comment]
Done.

**Comment by JasonLG1979** [comment]
I'm sorry, I have the attention span and organizational skills of a hamster on meth ;P

**Comment by gregsheremeta** [comment]
@MarkLodato please run the latest master and let us know if that fixed it for you.

**Comment by MarkLodato** [comment]
Thanks!  I'll try it out tomorrow and report back.

**Comment by gregsheremeta** [comment]
I put master through some pretty tough testing this morning, and it's rock solid. I'm confident that this is fixed now. I'll cut an Ubuntu release today.

Thanks @JasonLG1979 !

**Comment by MarkLodato** [comment]
Played 38 straight songs without a problem.  Thanks!

**Comment by ShapeShifter499** [comment]
I seem to have this issue still after the "fix" although it's not as bad as before. Some songs will fail to buffer or play anything but the client does not lock up and I can skip those "bad" songs.

**Comment by gregsheremeta** [comment]
We also have a buffering change almost ready to go. I wanted to release just the deadlock fix and see if that took care of all the known issues, though. Guess not.

@ShapeShifter499 can you post a screenshot of pithos when it's misbehaving? If we make a test branch for you, can you run it from source?

**Comment by ShapeShifter499** [comment]
@gregsheremeta I can once it messes up again, I'm currently listening again with no issues but it seems random. If you guys make it I can run it from source if need be, sure.

**Comment by ShapeShifter499** [comment]
@gregsheremeta when there is a issue it looks normal and everything works but the timer under the current song is missing and it never buffers or plays anything.

**Comment by gregsheremeta** [comment]
@ShapeShifter499 great, i was just wondering about the timer. I'll get back to you with something to try.

**Comment by ShapeShifter499** [comment]
@gregsheremeta here is that screenshot of the bug.
![screenshot_2015-05-13_07-16-52](https://cloud.githubusercontent.com/assets/388665/7612520/3c29dcf2-f940-11e4-8d1d-f21d525f8ddd.png)

**Comment by ShapeShifter499** [comment]
@gregsheremeta New bug maybe?  This time it just quit playing in the middle of a song, never continued to buffer or play anything. It did not lock up so I was able to just skip. Below is a screenshot of this.
![screenshot_2015-05-13_07-16-52](https://cloud.githubusercontent.com/assets/388665/7612567/82943804-f940-11e4-9a74-797772f36e39.png)

**Comment by Stebalien** [comment]
@ShapeShifter499 I've observed the same behavior.

**Comment by gregsheremeta** [comment]
@ShapeShifter499 just want to clarify -- are you seeing two different problems now?

1:
> it looks normal and everything works but the timer under the current song is missing and it never buffers or plays anything.

2: 
> quit playing in the middle of a song, never continued to buffer or play anything

**Comment by ShapeShifter499** [comment]
@gregsheremeta seems like two different issues now, yes.

**Comment by Stebalien** [comment]
@gregsheremeta I've only observed the second issue.

**Comment by ShapeShifter499** [comment]
@gregsheremeta In both issues the client never buffered or played any audio until I skipped the song in issue.

**Comment by ShapeShifter499** [comment]
@gregsheremeta Ok now I skipped a song I did not like and the timer carried over but the new song never played or buffered.  New screenshot below
![screenshot_2015-05-13_07-26-46](https://cloud.githubusercontent.com/assets/388665/7612745/889bbd34-f941-11e4-8418-194cf569771b.png)

**Comment by gregsheremeta** [comment]
Ok @ShapeShifter499, @Stebalien  got some code for you to test, if you would please. We think this will fix the buffering issues. Credit goes to @JasonLG1979 for two main ideas in this patch.

Instructions:

```
git clone https://github.com/pithos/pithos.git
cd pithos
git checkout WIP-testing-buffer
python3 -m pithos -vv
```

^ I need the log messages if / when you experience the issue.

**Comment by JasonLG1979** [comment]
Setting the buffer-size or buffer-duration causes gstreamer to error out if you drain the buffer after the initial buffering.(basically defeating half the purpose of having the buffer) I've pretty much abandoned that idea in favor of waiting for async-done and pull mode buffer handling.

**Comment by JasonLG1979** [comment]
I'm wondering if it's not a threading issue. Currently in Pithos the buffering function is being driven by an outside thread(gstreamer) strictly speaking every time an outside tread interacts with the main tread it should be done through a Glib timeout since neither python nor the GTK tool kit is thread safe. I'm wondering if the current buffering function isn't blocking the rest of Pithos. In my experience by putting a counter in the buffer function it updates at about 40 - 50 times a sec for mp3's and over 1000 times a sec for aac streams. Which is very excessive. My new buffer mechanism side steps the issue because it starts a timeout to query the buffer at a more reasonable 10 times a sec. A bonus side effect is that (on my machine anyway) CPU usage is cut in about half during buffering.

**Comment by gregsheremeta** [comment]
> Setting the buffer-size or buffer-duration causes gstreamer to error out if you drain the buffer after the initial buffering.

That can't be right. Maybe we're not handling that condition properly, but the design of gstreamer is that you can simply recover from a buffer underrun by setting play state to PAUSED and waiting for 100% again.

**Comment by JasonLG1979** [comment]
I tested it by starting a song and then disconnecting from my WiFi. With the properties set I get an error. Something about the URL being null. I don't remember exactly. Without the properties set the buffer reacts as expected and the song continues to play once I reconnect to WiFi.

**Comment by JasonLG1979** [comment]
Plus, the crazy amount of buffer fill hits that setting those properties were trying to avoid was caused by the download-buffer. Without the download-buffer enabled the buffer messages are much better behaved with the exception to the 0 to 100 thing for aac's, but that's a separate gstreamer bug.

**Comment by gregsheremeta** [comment]
Well let's see what @ShapeShifter499 and @Stebalien say about their results and go from there.

**Comment by ShapeShifter499** [comment]
@gregsheremeta @JasonLG1979 so far so good. I'm just playing music from Pandora/Pithos just as I usually would, skipping, liking, etc. and I have not experienced any issues yet with the test release of Pithos you gave me. I'm still listening and checking so I will let you know if I come across anything.

**Comment by gregsheremeta** [comment]
@ShapeShifter499 still looking good? @MarkLodato still good?

@Stebalien @xguse had a chance to try it?

**Comment by ShapeShifter499** [comment]
@gregsheremeta Still looking good.

**Comment by gregsheremeta** [comment]
Alright, I'm going to release a 1.0.3 and 1.1.1 with this fix in there.

@JasonLG1979 buffer underrun recovery is working fine for me. I tested it with both MP3s and AACs of varying quality. Instead of killing the network connection, I throttled a local apache server until it caused pithos to buffer. See [this video](https://www.youtube.com/watch?v=NPl8iv4AzvM).

**Comment by gregsheremeta** [comment]
@ShapeShifter499 / everyone else, can you fetch the latest master and try that out for a few days?

**Comment by JasonLG1979** [comment]
> buffer underrun recovery is working fine for me. I tested it with both MP3s and AACs of varying quality. Instead of killing the network connection, I throttled a local apache server until it caused pithos to buffer. See this video.

@gregsheremeta You're right, my bad. It was setting the 'buffer-duration' property that caused the errors. 'buffer-size' works just fine. But my original math was wrong. If you're basing your numbers off mine it should be 'BUFFER_SIZE = (192 * 1000)/8 * 3' to get 3 secs of buffer at 192kbit/s. I forgot to convert bits to bytes,lol!!!

**Comment by gregsheremeta** [comment]
@JasonLG1979 I believe `buffer-duration` is intended to be read-only. The docs are very unclear about it. So I'm not surprised that would kill gstreamer.

**Comment by gregsheremeta** [comment]
> I forgot to convert bits to bytes

Yeah me too. I'll fix. thanks.

**Comment by JasonLG1979** [comment]
> I believe buffer-duration is intended to be read-only. The docs are very unclear about it. So I'm not surprised that would kill gstreamer.

You can set it. After you set it if you print self.player.get_property('buffer-duration') it reflects the change. But I agree the docs the gstreamer docs pretty much suck.

**Comment by JasonLG1979** [comment]
Spoke to soon. If I disconnect form wifi without setting the buffer-size it works as expected. Pauses until I reconnect and then picks backup where it left off once the buffer refills.

If I disconnect with the buffer-size set I get this. - 
```ERROR - pithos:on_gst_error:681 - Gstreamer error: gst-resource-error-quark: Could not resolve server name. (3), gstsouphttpsrc.c(1491): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin5/GstSoupHTTPSrc:source:
Error resolving 't3-2.p-cdn.com': Temporary failure in name resolution (2), URL: http://t3-2.p-cdn.com/access/74829663799281218.mp3?version=4&lid=268249233&token=u9VkeIfRE9DJvQsiP%2FL51TyIiTZcQMSZeVrg5xS3N6MyGW2p%2FbdjLIterv4z%2FcmX9lzQMTs3WUs6Qu49yLazsbuvwRWmYpTc2FrsuJJJQ83shnaAxNcyo%2FQhK8hNB%2BmyY6qorPqPhCjPg1fBxDrD8l9%2Filg1vNFuYaUMinKWclOBHKhSAygkH4km%2BM1yGaPh%2B8CED4lt39JD4PGw6%2Fur41fSutjwRaKImjN981T8e1sgsTpn%2Fge9sRfXs%2B%2FkLoishyr2%2BIf2657Fr4oWUo5LfSzfGdxS7XZjSe5khtw5e9awPyt4LCFvCZ%2BuvC459QtYwA01bVqOXn%2FwHNz7f30zruonFwJGfVVj5CJGy4foXtmY3yDaP55CAxsDAGOa5Gz1, Redirect to: (NULL), 3
INFO - pithos:start_song:458 - Starting song: index = 6
INFO - pandora:audioUrl:372 - Using audio quality highQuality: 192 mp3
ERROR - pithos:on_gst_error:681 - Gstreamer error: gst-resource-error-quark: Could not resolve server name. (3), gstsouphttpsrc.c(1491): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin6/GstSoupHTTPSrc:source:
Error resolving 't3-2.p-cdn.com': Temporary failure in name resolution (2), URL: http://t3-2.p-cdn.com/access/7630043379497437725.mp3?version=4&lid=268249233&token=u9VkeIfRE9DJvQsiP%2FL51TyIiTZcQMSZeVrg5xS3N6MyGW2p%2FbdjLIterv4z%2FcmX9lzQMTs3WUs6Qu49yLazsb%2FQ64Men4h1uEIRg3S3pOaVHd8bMVYDnEZmM1CrAdGQQLIrQihqyrM4jkr0RGpIN0IwFemh7gFR9JphDbh19gkcRuElIqc2TSLLTnGRZkoZRjqlD0wxWv3Qm5sTVlqNh%2BYSEb5xRpsHAU5CO5I4fSPqkBEOHF2vUuf7kb3RsEdd%2FIS0upa9tc7yLEXmq7KxD%2B3nw5tISA6OZ497TGEcCmKgl9DNQT%2BqFOWoC%2FX6G1WZTpcER4URjCmxx4TESyCyUZyUB8Sp5%2Bdggp%2FJwKW34dZIKd5A3WiFA1O%2B3jwNAZLY, Redirect to: (NULL), 3
INFO - pandora:get_playlist:287 - pandora: Get Playlist
DEBUG - pandora:json_call:113 - https://internal-tuner.pandora.com/services/json/?partner_id=37&user_id=268249233&auth_token=VIVFbSU8eR3GvgROZe4EIPlr9xLTx7uzzjN2STTrcls3fR8ZjNM7pxfQ%3D%3D&method=station.getPlaylist
DEBUG - pandora:json_call:114 - b'{"stationToken": "2063492698051782801", "userAuthToken": "VIVFbSU8eR3GvgROZe4EIPlr9xLTx7uzzjN2STTrcls3fR8ZjNM7pxfQ==", "syncTime": 1431716429}'
ERROR - pandora:json_call:127 - Network error: <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.1.0-py3.4.egg/pithos/plugins/lastfm.py", line 81, in song_ended
    self.scrobble(song)
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.1.0-py3.4.egg/pithos/plugins/lastfm.py", line 105, in scrobble
    if duration > 30 and (position > 240 or position > duration/2):
TypeError: unorderable types: NoneType() > int()
INFO - pithos:start_song:458 - Starting song: index = 7
INFO - pandora:audioUrl:372 - Using audio quality highQuality: 192 mp3
ERROR - pithos:on_gst_error:681 - Gstreamer error: gst-resource-error-quark: Could not resolve server name. (3), gstsouphttpsrc.c(1491): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin7/GstSoupHTTPSrc:source:
Error resolving 'audio-ch1-t2-1-v4v6.pandora.com': Temporary failure in name resolution (2), URL: http://audio-ch1-t2-1-v4v6.pandora.com/access/3314022609975324724.mp3?version=4&lid=268249233&token=u9VkeIfRE9DJvQsiP%2FL51TyIiTZcQMSZeVrg5xS3N6MyGW2p%2FbdjLIterv4z%2FcmX9lzQMTs3WUs6Qu49yLazsSSiIC1uNBvf4%2BRO964uJJpi5xW3BgujRzri09pCNQtBDZKqPaY6WY4jYK7rCS%2FfC9wYOMcWAVVO30ScH9Oj0RPOfnTMPL6LosFPhGCWHAunoTEo7SbWabGr5V02hRggmc6oLr1UhKcE7e%2FGlVLS%2BGIn2RPFrovGxDS6CbSdbsn3YjEyQezsIpGxg8LS3hDs2jAKi5c3mMeQfRPIpgdoMNuKQ18wml6HeNKuzjV1b76LyTGbQqEMEwrdpgSZnWy1iPZyD79j9XK0UVJlgcAjRJK95doWkFoMrtrzbNDejzF1, Redirect to: (NULL), 3
ERROR - pithos:on_gst_error:681 - Gstreamer error: gst-resource-error-quark: Could not resolve server name. (3), gstsouphttpsrc.c(1491): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin7/GstSoupHTTPSrc:source:
Error resolving 'audio-ch1-t2-1-v4v6.pandora.com': Temporary failure in name resolution (2), URL: http://audio-ch1-t2-1-v4v6.pandora.com/access/3314022609975324724.mp3?version=4&lid=268249233&token=u9VkeIfRE9DJvQsiP%2FL51TyIiTZcQMSZeVrg5xS3N6MyGW2p%2FbdjLIterv4z%2FcmX9lzQMTs3WUs6Qu49yLazsSSiIC1uNBvf4%2BRO964uJJpi5xW3BgujRzri09pCNQtBDZKqPaY6WY4jYK7rCS%2FfC9wYOMcWAVVO30ScH9Oj0RPOfnTMPL6LosFPhGCWHAunoTEo7SbWabGr5V02hRggmc6oLr1UhKcE7e%2FGlVLS%2BGIn2RPFrovGxDS6CbSdbsn3YjEyQezsIpGxg8LS3hDs2jAKi5c3mMeQfRPIpgdoMNuKQ18wml6HeNKuzjV1b76LyTGbQqEMEwrdpgSZnWy1iPZyD79j9XK0UVJlgcAjRJK95doWkFoMrtrzbNDejzF1, Redirect to: (NULL), 3
ERROR - pithos:on_gst_error:681 - Gstreamer error: gst-stream-error-quark: Internal data flow error. (1), gstbasesrc.c(2933): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin7/GstSoupHTTPSrc:source:
streaming task paused, reason error (-5), 1
ERROR - gobject_worker:_default_errorback:48 - Unhandled exception in worker thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.1.0-py3.4.egg/pithos/gobject_worker.py", line 35, in _run
    result = command(*args)
  File "/usr/lib/python3/dist-packages/pylast.py", line 4303, in report_now_playing
    self.nowplaying_url, params, self.network
  File "/usr/lib/python3/dist-packages/pylast.py", line 4203, in execute
    connection.request("POST", self.subdir, data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

ERROR - gobject_worker:_default_errorback:48 - Unhandled exception in worker thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.1.0-py3.4.egg/pithos/gobject_worker.py", line 35, in _run
    result = command(*args)
  File "/usr/lib/python3/dist-packages/pylast.py", line 4303, in report_now_playing
    self.nowplaying_url, params, self.network
  File "/usr/lib/python3/dist-packages/pylast.py", line 4203, in execute
    connection.request("POST", self.subdir, data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution```

**Comment by gregsheremeta** [comment]
I think it's reasonable that the streaming is stopping because of the network errors it's reporting.

Handling buffer underrun is an expected, normal condition, and something we handle nicely (now).

The network dying and/or DNS becoming unavailable is an exceptional condition -- not necessarily one we should be expected to seamlessly recover from.

Feel free to open a bug on handling network outages, but I don't think it's part of the buffering work.

**Comment by JasonLG1979** [comment]
> Feel free to open a bug on handling network outages, but I don't think it's part of the buffering work.

I don't think I'll open a bug because the solution to not being able to recover from network outages is to remove the buffer-size setting. ;P

It recovered from network outages just fine before now not so much...

**Comment by ShapeShifter499** [comment]
@gregsheremeta If I understand what I'm reading in the git repo, the fix is included but the version number hasn't been changed. Just letting you know.

**Comment by gregsheremeta** [comment]
You're right. We had a couple more tweaks on top of the fix. I just wanted some additional confirmation.

**Comment by MarkLodato** [comment]
So far so good.  I haven't been listening a lot (only a few hours) but I haven't had one problem yet.

**Comment by gregsheremeta** [comment]
> I don't think I'll open a bug because the solution to not being able to recover from network outages is to remove the buffer-size setting

@JasonLG1979 Shrug, I'm not seeing that. Were you on master, or your branch? If your branch, there are so many changes in there, I'm thinking something else was the cause. Not sure.

I can cause a network outage locally and master recovers perfectly.

```
DEBUG - pithos:handler:687 - Found tag "maximum-bitrate" in stream: "319725" (type: <class 'int'>)
DEBUG - pithos:on_gst_buffering:730 - Buffering (6%)
DEBUG - pithos:on_gst_buffering:736 - Buffer underrun. Pausing pipeline
DEBUG - pithos:on_gst_buffering:730 - Buffering (12%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (17%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (23%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (29%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (34%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (40%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (46%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (51%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (57%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (63%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (68%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (74%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (80%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (85%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (91%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (97%)
DEBUG - pithos:on_gst_buffering:730 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:744 - Buffer recovery. Restarting pipeline
```

Our two testers are happy with master, so I'm going to cut a 1.0.3 and 1.1.1.

**Comment by JasonLG1979** [comment]
Nope. I was using the stock Pithos master.

**Comment by gregsheremeta** [comment]
Shrug, no clue. Even if increasing the buffer-size does cause issues with recovery in the event of an outage, I'm happy to make that tradeoff at this point. I want to get a quick fix out to users, and master seems really solid.

I assume our next big release will include Glenn's player refactor.

**Comment by gregsheremeta** [comment]
Well, I changed my mind. Setting buffer-size seems to have no positive effect for me. Setting buffer-duration actually grows the buffer in use. But since master is working without buffer-duration set, I'm going to remove buffer-size.

**Comment by JasonLG1979** [comment]
I think it was worth a shot,  but probably a dead end. You're mileage it seems varies, but for me in Ubuntu 15.04 setting the buffer-duration causes the same errors in the event of a a network outage.

**Comment by JasonLG1979** [comment]
I've got some non buffer related stuff I might send your way in the next couple days. Like using the info that Pandora provides for the duration, codec, and bitrate in the UI. It's generally just cosmetic stuff but I think it makes for a smoother looking/acting UI. Namely It means all that stuff would be known a head of time and therefor displayed as soon as the song changed instead of like now and having a second or 2 before it's know and shows up in the UI.

**Comment by gregsheremeta** [comment]
Ok. Since this buffering fire is soon to be out, I suggest we start focusing on @glennimoss's branch. I need to study it.

**Comment by JasonLG1979** [comment]
His branch doesn't work in Ubuntu 15.04.

**Comment by gregsheremeta** [comment]
Ok. Let's take this to IRC so we don't spam everyone...

**Comment by gregsheremeta** [comment]
closing. 1.1.1 is in the PPA. I'll push 1.0.3 tomorrow.

**Comment by gregsheremeta** [comment]
1.0.3 and 1.1.1 are both available via ppa (Ubuntu) and copr (Fedora). Thanks for bearing with us, and please reopen if there are any more issues.

**Comment by levibostian** [comment]
Hello there. I am still having this issue. Here are some details: 

* Pithos v1.2.1
* Raspberry Pi 2
* Ubuntu Mate 16.04 
* Wired ethernet connection and I have tried WiFi connection. Both connections 50+ mbps lines. 
* Pandora account *not* One subscription. 
* Running Pithos from terminal and no warnings thrown in standard output. 
* Desktop running with no screensaver, no sleep, etc. Always up and running. 
* Pithos no plugins installed. No proxy. Explicit music allowed. 

Same issue as this issue was initially having issues with. Pithos will play great for 20 - 60 minutes then randomly it will get to a song and not play. No issues stopping halfway into a song, but not playing the next song in station.

**Comment by JasonLG1979** [comment]
What version of Gstreamer? I haven't seen this issue on x86-64 Gstreamer since maybe 1.4? I just so happen to have a Raspberry Pi 2. I might be able to do some testing this weekend.

**Comment by JasonLG1979** [comment]
Also aac or mp3 stream?

**Comment by levibostian** [comment]
@JasonLG1979 I don't believe gstreamer was installed. I just did on the raspberry pi via: `sudo apt-get install gstreamer1.0` I am assuming it was installed before however or Pithos would not work without it?

I am not sure if I am using aac or mp3. Not sure how to change. I have the preferences set for Medium quality. I can change it to whatever works best.

**Comment by levibostian** [comment]
Something interesting. I had Pithos running on the Raspberry Pi 2 in it's broken state of not playing/paused/frozen/whatever you want to call it. 

I opened up a new terminal window, typed `gstr` then TAB to auto complete `gstreamer` if it was available then Pithos immediately started playing again. Coincidence? Maybe? Seems that I woke up gstreamer or something. Seems too good to be true however it was so crazy how it happened, had to include it. 

---

It then proceeded to play through some of a song then skip to the next song showing `gst-resource-error-quark: Forbidden (15)`, went to the next song automatically, that one skipped showing `gst-streamer-error-quark: Stream doesn't contain enough data: (4)`, then went to the next song automatically. That song played through successfully, got to the next song where it again, stopped playing at 0:00.

**Comment by JasonLG1979** [comment]
> I don't believe gstreamer was installed.

Some version of Gstreamer was previously installed Pithos would not work at all without it.

Gstreamer 1.x will always show up as gstreamer1.0 to denote it's a part of the 1.x branch as opposed to the 0.10 branch. That's not the version number.

What is the output of:
```bash 
apt-cache show gstreamer1.0 | grep Version
```
That should show you your Gstreamer version.

How did you install?

**Comment by JasonLG1979** [comment]
btw. The "High" audio quality is 128kbit/s mp3. They seem to do better than aac's ("Medium" and "Low" are aac's)

**Comment by JasonLG1979** [comment]
According to this:
https://launchpad.net/ubuntu/+source/gstreamer1.0
You should have Gstreamer 1.8 installed.

I'll run on the Medium quality for a while and see if I can reproduce the bug on Fedora 24 64-bit. It may be a armhf specific bug?

**Comment by levibostian** [comment]
GStreamer 1.8 is installed, correct. 

Installed Pithos via `apt-get` copy/paste from website. 

I changed quality to High over Medium. Probably still persists. 

I just watched it more closely. Pithos just stopped playing at 0:00 again. When it stopped, the bottom of Pithos said "Getting songs..." then that song stopped at 0:00. Might have something to do it with it

**Comment by JasonLG1979** [comment]
You got Pithos v1.2.1 from the stock repo?
According to this:
http://packages.ubuntu.com/search?keywords=pithos
The stock repo has v1.1.1

But it really doesn't matter I don't think anything changed in the audio bits.

Try running Pithos with Gstreamer debugging enabled with:
```bash
 GST_DEBUG=5 pithos
```
It will spilt A LOT out if it's more than the Raspberry Pi2 can handle it run:
```bash
 GST_DEBUG=3 pithos
```

We don't need the whole output just the error(s) that happen before it locks up.

**Comment by JasonLG1979** [comment]
So far I get the following warnings on Medium Quality(aac). Not sure if they are spam or apart of your problem. So far I have had no freezes. I'll let it run over night and check it in the morning to see if I run into the same problems you decribe.

```bash
qtdemux qtdemux_types.c:222:qtdemux_type_get: unknown QuickTime node type iods
qtdemux qtdemux.c:2651:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 1
```

**Comment by levibostian** [comment]
Output of `GST_DEBUG=2 pithos`:

![img_20160830_072138](https://cloud.githubusercontent.com/assets/2041082/18090769/fc0ef75c-6e8b-11e6-9a78-e07174735812.jpg)

I circled the bottom 2 warnings (4 in total). The bottom 2 are output from when Pithos stopped at 0:00 after 6-8 songs. Those are the messages you are looking for, @JasonLG1979. 

The top 2 were actually thrown when Pithos first started up. When Pithos first starts, sometimes music starts playing and sometimes it doesn't (this time it didn't. It was stuck at 0:00 on Quickmix. I changed the station and it started playing just fine). Top 2 warnings were thrown when Pithos started, last 2 are after 6-8 songs when Pithos stopped at 0:00.

**Comment by JasonLG1979** [comment]
I get the same warnings. I don't think that's the problem. 

What are you using as an audio output. The pi's have nutritiously crappy audio. Do me a favor, this sounds weird but open something that also plays audio along with Pithos to see if all audio takes a crap when Pithos locks up.

**Comment by JasonLG1979** [comment]
This is starting to look like a pulse audio crash.

**Comment by levibostian** [comment]
I am using the Raspberry Pi audio jack as the output. I have not edited audio settings on the OS. Just installed Mate then installed Pithos. 

I am running Pithos and Rythmbox together right now. Here are my findings so far:

1. Turn on Rythmbox, start a song, put on endless repeat. 
2. Open Pithos, start station. Both play together, both tracks come through and sound fine. 
3. After the Rythmbox song ends, it starts over just fine. BUT after the Pithos song ends, it stops, hits 0:00 and stops playing as usual. The terminal throws the same warning for Pithos as before: `pulse pulseink.c:702:gst_pulsering_stream_underflow_cb:<pulseink1> Got underflow`

**Comment by JasonLG1979** [comment]
I get the same warning but no freeze on Fedora 24.

**Comment by levibostian** [comment]
Fedora on Raspberry Pi 2? I will switch distros if needed. I just need Pithos to run all day on a Raspberry Pi 2 however that needs to be done I can make it work.

**Comment by JasonLG1979** [comment]
No Fedora on my PC. I haven't had a chance to test on my pi yet.

**Comment by JasonLG1979** [comment]
I'm just trying to compare. I'll fire up Ubuntu x86_64 in boxes and throw Ubuntu mate on my pi. What I'm going to try to do is narrow down where the issue is. Is it Ubuntu specific or is it Ubuntu armhf specific? It works fine in Fedora 24. So somethings up with Ubuntu somehere.

**Comment by JasonLG1979** [comment]
It might be a bit though. I'm currently at the dentist getting a wisdom tooth surgically extracted.

**Comment by levibostian** [comment]
Wow. Get your teeth taken care of then get back to me. No sweat, Jason. 

To reproduce, I will say exactly what I have done:

1. Raspberry Pi 2
2. Ubuntu Mate 16.04.1 LTS Raspberry Pi edition:
<img width="1196" alt="screenshot 2016-08-30 12 32 35" src="https://cloud.githubusercontent.com/assets/2041082/18099820/f3ec183a-6ead-11e6-87e9-b17177298cb6.png">
3. Install on Pi, go through Ubuntu setup, etc. 
4. Install Pithos through PPA
```
sudo add-apt-repository ppa:pithos/ppa
sudo apt-get update
sudo apt-get install --install-recommends pithos
```
5. Login Pandora (regular account. Not One subscription). Audio quality set to High. 
6. Only other thing I did was setup Ubuntu power settings to not sleep or turn off screen. It's plain ol' unmodified Ubuntu with Pithos on it. 

Thanks! I have used Pithos for years on Lubuntu, Ubuntu, Xubuntu no issues. On the Raspberry Pi is where my issues have just started.

**Comment by JasonLG1979** [comment]
No worries the extraction is done when off without a hitch. Besides half my face is still numb,lol!!!

Do you have any issues with x86/x86_64 version of Ubuntu and Pithos? I have not tested Pithos in Ubuntu on real install in a while?

**Comment by levibostian** [comment]
I do not have a Ubuntu machine anymore to test it on, sorry. When I had my laptop that had Ubuntu installed with x86_64, it worked great no issues at all. That was also 6 months ago minimum.

**Comment by levibostian** [comment]
Any luck with installing Pithos on a raspberry pi yet, @JasonLG1979?

**Comment by JasonLG1979** [comment]
Sorry about that. Had a busy weekend. I'm doing it right now.

**Comment by JasonLG1979** [comment]
Sorry about that. Had a busy weekend. I'm doing it right now.

**Comment by JasonLG1979** [comment]
Sorry about that. Had a busy weekend. I'm doing it right now.

**Comment by JasonLG1979** [comment]
Well I managed to get Ubuntu Mate installed on my rpi2(geez I forgot how slow they were as a desktop system). I installed Pithos from the latest source and I get the same thing. A lot of the time the song will fully buffer and then just sit there. I am able to press play and it will play though. Debugging gsteamer is no help and after poking around in Pithos I'm stumped. The song fully buffers and hits the play method and according to gstreamer the state change to playing is successful. It SHOULD be playing at that point.

**Comment by JasonLG1979** [comment]
@levibostian start a new issue. This seems like something new.

**Comment by levibostian** [comment]
@JasonLG1979 [created](https://github.com/pithos/pithos/issues/342)

**Comment by theAntiBob** [comment]
It seems this thread has gone a bit off topic? I've been having the same symptom as the screenshot, pithos buffers to 100% and remains at 0:00/X:XX with no pause indicator. Pause/play has no effect, skipping to the next track just does the same thing. Everything WAS working fine, then i had to make some modifications to (i think) default.pa (pulseaudio settings file) to duplicate R&L speakers on RR&RL (surround)

long story short, if pulse module peak detect (start pavucontrol or pavumeter) is running, songs play, next song plays, etc. kill that vumeter and back to the original issue.
killall pulseaudio or pulseaudio -k gives an error (in pithos), skips that track, then starts playing the next song just fine. at which point launching pulsemodule_peak_detect (any way) will let it continue playing normally.
dont think playbin has anything to do with this, pretty sure this is one of pulseaudio's MANY problems.
dont get me wrong here, i use pulse knowingly and will not be crying like a baby about how much "better" it is to just use alsa.
anyone out there know enough about pulse to help me(ALL OF US) get the settings right to fix this?
i've overcome this issue in the past, but don't have time/cant track down the info that lead me to the solution.

also hope this at least helps some people figure out the "killall pulseaudio" / pavumeter workaround i've been using in the mean time

**Comment by bkw777** [comment]
I've been having the issue for several months at least, and it didn't change better or worse after I replaced pulseaudio with pipewire, so it's not pulseaudio. It gets to the end of a song and hangs instead of loading the next song. Pressing the next/ff button does load the next song. At this moment it's doing ity on almost every song, but typically it's a bit random. Might play for an hour straight and then hang, or might hang once every 3 or 4 songs.

**Comment by may** [comment]
Same here.
Unchecked pause on screensaver, and any other extra setting and could not narrow it down. It just plain stops.
v 1.1.2 on Ubuntu 22.04 via Pop_OS
I'm sure it will get fixed at some point, in the meantime there is pianobar!
(Since pithos is based on pianobar, I assume it's a bug in the UI layer of pithos, but I am simply guessing; pianobar works)

**Comment by wpietri** [comment]
I was also having a problem with v 1.1.2 on Ubuntu 22.04, and the solution is to install the current version, 1.6.1, via Flatpak: `https://github.com/pithos/pithos/releases/tag/1.6.2`.

**Comment by cadteach1** [comment]
I believe this may be fixed.  I've been listening to v. 1.1.2 on MX Linux (uses Debian) and have not had any stuck/pause between songs all day, when I used to have this pretty regularly every 5 or so songs, or more frequent.  Is there any system information that would help anyone?  MX Linux has sort of a updates when Debian does, and doesn't really update software, I believe.  Anyway, I'm happy its working because I enjoy the software and like listening with it versus browser tab or whatever.
